# Generated by Django 6.0.2 on 2026-03-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='sexo',
            field=models.IntegerField(choices=[(0, 'Prefiero no decir'), (2, 'Hombre'), (1, 'Mujer')], default=2),
        ),
    ]
